export const SET_QUOTATION_DOLAR = 'SET_QUOTATION_DOLAR';
export const SET_QUOTATION_EURO = 'SET_QUOTATION_EURO';
export const SET_QUOTATION_REAL = 'SET_QUOTATION_REAL';
export const SET_LOADING = 'SET_LOADING';